# coding=utf-8
import Qichacha_WeiXin_EsConvert


def test_convert():
    test_source = u'''
    {
    "status":200,
    "message":"成功",
    "result":{
        "CountInfo":{
            "IsIndividual":false,
            "InvesterCount":0,
            "ShiXinCount":0,
            "ShiXinNewCount":0,
            "ZhiXingCount":0,
            "ZhiXingNewCount":0,
            "SAICCount":0,
            "SAICNewCount":0,
            "AnnualReportCount":2,
            "AnnualReport":"2015年度报告, 2014年度报告",
            "PatentCount":0,
            "PatentNewCount":0,
            "CTACount":0,
            "CTANewCount":0,
            "JudgementCount":0,
            "JudgementNewCount":0,
            "CertificateCount":0,
            "SoftCRCount":0,
            "WorkCRCount":0,
            "WebCount":0,
            "CerCategoryCount":0,
            "NewsCount":0,
            "RecruitCount":0,
            "FinancingCount":0,
            "ProductCount":0,
            "FinanceCount":0,
            "TaxCount":0,
            "RelationCount":0,
            "FinancingTaxCount":0,
            "CompanyInfoCount":0,
            "ViewCount":14,
            "CommentCount":0,
            "FollowCount":0
        },
        "Status":1,
        "Message":null,
        "Company":{
            "TermStart":"2014-07-09T00:00:00+08:00",
            "TeamEnd":null,
            "CheckDate":"2014-07-09T00:00:00+08:00",
            "Partners":[
                {
                    "Org":1022,
                    "SeqId":1,
                    "CompanyId":null,
                    "StockName":"华威",
                    "StockType":"境内中国公民",
                    "StockPercent":"35.00%",
                    "IdentifyType":"身份证",
                    "IdentifyNo":null,
                    "ShouldCapi":null,
                    "ShoudDate":null,
                    "InvestType":null,
                    "InvestName":null,
                    "RealCapi":null,
                    "CapiDate":null,
                    "Address":null,
                    "CapiRate":"35.00%"
                },
                {
                    "Org":1022,
                    "SeqId":1,
                    "CompanyId":null,
                    "StockName":"顾挺",
                    "StockType":"境内中国公民",
                    "StockPercent":"35.00%",
                    "IdentifyType":"身份证",
                    "IdentifyNo":null,
                    "ShouldCapi":null,
                    "ShoudDate":null,
                    "InvestType":null,
                    "InvestName":null,
                    "RealCapi":null,
                    "CapiDate":null,
                    "Address":null,
                    "CapiRate":"35.00%"
                },
                {
                    "Org":1022,
                    "SeqId":2,
                    "CompanyId":null,
                    "StockName":"马军",
                    "StockType":"境内中国公民",
                    "StockPercent":"30.00%",
                    "IdentifyType":"身份证",
                    "IdentifyNo":null,
                    "ShouldCapi":null,
                    "ShoudDate":null,
                    "InvestType":null,
                    "InvestName":null,
                    "RealCapi":null,
                    "CapiDate":null,
                    "Address":null,
                    "CapiRate":"30.00%"
                }
            ],
            "Employees":[
                {
                    "No":1,
                    "Name":"顾挺",
                    "Job":"执行董事",
                    "CerNo":null,
                    "ScertName":null
                },
                {
                    "No":2,
                    "Name":"华威",
                    "Job":"监事",
                    "CerNo":null,
                    "ScertName":null
                },
                {
                    "No":3,
                    "Name":"顾挺",
                    "Job":"总经理",
                    "CerNo":null,
                    "ScertName":null
                }
            ],
            "Branches":[

            ],
            "ChangeRecords":[

            ],
            "AnnualReports":null,
            "ContactInfo":{
                "PhoneNumber":"18961719157"
            },
            "StockHolders":[

            ],
            "Exceptions":[

            ],
            "Area":{
                "Province":"江苏省",
                "City":"无锡市",
                "County":"南长区"
            },
            "Pledge":[

            ],
            "Penalty":[

            ],
            "SpotCheck":[

            ],
            "MPledge":[

            ],
            "Liquidation":{

            },
            "Name":"无锡街库网络科技有限公司",
            "No":"320203000123503",
            "BelongOrg":"无锡市南长区市场监督管理局",
            "OperName":"顾挺",
            "StartDate":"2014-07-09",
            "EndDate":null,
            "Status":"在业",
            "Province":"JS",
            "UpdatedDate":"2016-09-10",
            "ShortStatus":"在业",
            "CreditCode":null,
            "RegistCapi":"10万元",
            "EconKind":"有限责任公司",
            "Address":"无锡市南长区沁园新村868号227",
            "Industry":{
                "IndustryCode":"M",
                "SubIndustryCode":73,
                "Industry":"研究和试验发展",
                "SubIndustry":"研究和试验发展"
            },
            "Scope":"计算机、软件及辅助设备的研究与开发、技术咨询、技术服务、技术转让及销售；信息系统集成服务；贸易咨询服务；网页设计服务。 （依法须经批准的项目，经相关部门批准后方可开展经营活动）",
            "ImageUrl":"http://co-image.qichacha.com/CompanyImage/default.jpg",
            "OrgNo":"39824469-6",
            "EnglishName":null,
            "Unique":"d4dcc89d0b686b6e0060fc43271bb581",
            "ShortEconKind":"有限责任公司",
            "companyExtendInfo":{

            },
            "IsFocus":false,
            "IsCert":"0",
            "GroupId":"",
            "CompanyTemplate":"0",
            "profile":{
                "profileDesc":"",
                "companyRange":"",
                "industry":""
            }
        },
        "UpdateTime":"2016-09-10",
        "subtitle":{
            "Info":{
                "clickFlag":true,
                "title":"有#0$次变更记录"
            },
            "Pledge":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "Penalty":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "SpotCheck":{
                "title":"企业抽查检查信息",
                "clickFlag":false
            },
            "MPledge":{
                "title":"企业动产抵押信息",
                "clickFlag":false
            },
            "Exceptions":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "Finances":{
                "title":"共#0$期",
                "clickFlag":false
            },
            "Taxes":{
                "title":"共#0$个年度",
                "clickFlag":false
            },
            "PossibleRelationship":{
                "title":"相关企业信息",
                "clickFlag":true
            },
            "InvestRelation":{
                "title":"#3$股东,#0$对外投资",
                "clickFlag":true
            },
            "AnnualReport":{
                "title":"2015, 2014",
                "clickFlag":true
            },
            "PicMap":{
                "title":"直观展示企业关系",
                "clickFlag":true
            },
            "CTA":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "Zhixing":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "Shixin":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "Judgement":{
                "title":"共#0$件",
                "clickFlag":false
            },
            "Patent":{
                "title":"共#0$个",
                "clickFlag":false
            },
            "SAIC":{
                "title":"共#0$个",
                "clickFlag":false
            },
            "CR":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "Website":{
                "title":"共#0$个",
                "clickFlag":false
            },
            "RoadMap":{
                "title":"一步步足迹呈现",
                "clickFlag":true
            },
            "News":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "Recruit":{
                "title":"共#0$个",
                "clickFlag":false
            },
            "Certificate":{
                "title":"共#0$条",
                "clickFlag":false
            },
            "FinancingReport":{
                "title":"共#0$次",
                "clickFlag":false
            },
            "ProductInfo":{
                "title":"共#0$个",
                "clickFlag":true
            }
        }
    }
}
    '''

    result = Qichacha_WeiXin_EsConvert.convert(test_source)
    assert result is not None


if __name__ == '__main__':
    test_convert()
