# encoding=utf-8
import json

import QinxinWeixinEsConvert

if __name__ == '__main__':
    basice_info = u'''
    {
        "reg_no":"530000000002414",
        "credit_no":"915300007414512392",
        "org_no":"741451239",
        "name":"云南盐化股份有限公司",
        "econ_kind":"股份有限公司(上市)",
        "scope":"盐及其系列产品的开发、加工和销售；化工盐及其系列产品的开发加工销售；食品添加剂盐酸、食品添加剂氢氧化钠（液体）；日用化工产品，化妆品，盐包装材料、防伪＂碘盐标志＂，无水硫酸钠的生产、加工和销售、盐业技术的开发、咨询服务；批发、零售副食品，建筑、装饰材料；氯碱化工及其系列产品、化工产品及其原料、合成树脂及塑料制品的生产和销售，其它有机及精细氯产品（以上项目涉及危险化学品的须凭相关许可证经营）；原辅料、仪器仪表、机械设备、零配件的经营业务；经营本企业自产产品及技术的出口业务。经营生产性原辅材料、仪器仪表、机械设备、零配件及技术的进口业务（国家限定公司经营和国家禁止进出口的商品除外）钻井，机电机械产品制造、修理、安装；氯化钠、硫酸钠采矿（凭许可证经营）；铁路专用线共用业务；现代物流配送，代理经营配套设施建设及连锁经营；一、二类压力容器设计、制造、安装，水力发电投资，锅炉安装（B级）压力管道安装（ＣC2级）；液氯、硫磺、氟硅酸钠、磷酸、腐蚀品的批发。酒类经营、日用百货、预包装食品、散装食品及粮油制品的批发零售。饲料、硅锰合金、硫酸的销售；硫酸的生产（限分支机构）；农产品及农副产品的销售。",
        "term_start":"2002-07-25",
        "term_end":"-",
        "check_date":"2015-11-30",
        "belong_org":"云南省工商行政管理局",
        "oper_name":"杨万华",
        "start_date":"2002-07-25",
        "end_date":"-",
        "status":"存续（在营、开业、在册）",
        "regist_capi":"27,916.4668 万人民币",
        "province":"YN",
        "addresses":[
            {
                "name":"注册地址",
                "address":"云南省昆明市官渡区春城路276号",
                "postcode":""
            }
        ],
        "parameters":"",
        "last_update_time":"07月15日",
        "logo_url":"",
        "partners":[
            {
                "seq_no":1,
                "eid":"06e0e3f8-315f-4043-9817-b510831a25c0",
                "stock_name":"云南轻纺集团有限公司",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[
                    {
                        "shoud_capi":"1,627.4 万人民币",
                        "should_capi_date":"2008年4月10日",
                        "invest_type":"货币"
                    }
                ],
                "real_capi_items":[
                      {
                        "real_capi":"1,627.4 万人民币",
                        "real_capi_date":"-",
                        "invest_type":"货币"
                    }
                ]
            },
            {
                "seq_no":2,
                "eid":"73e79e5e-53d5-45d6-b4b9-1c79226c1bed",
                "stock_name":"中国盐业总公司",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[

                ],
                "real_capi_items":[

                ]
            },
            {
                "seq_no":3,
                "eid":"",
                "stock_name":"云南有色地质矿业有限公司",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[

                ],
                "real_capi_items":[

                ]
            },
            {
                "seq_no":4,
                "eid":"1a5d26c4-d118-4252-963d-ec6bac98c3c6",
                "stock_name":"安宁市工业总公司",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[

                ],
                "real_capi_items":[

                ]
            },
            {
                "seq_no":5,
                "eid":"",
                "stock_name":"云南省国有资产经营有限责任公司",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[

                ],
                "real_capi_items":[

                ]
            },
            {
                "seq_no":6,
                "eid":"",
                "stock_name":"云南省开发投资有限公司",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[

                ],
                "real_capi_items":[

                ]
            },
            {
                "seq_no":7,
                "eid":"",
                "stock_name":"社会公众股",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[

                ],
                "real_capi_items":[

                ]
            },
            {
                "seq_no":8,
                "eid":"3192248d-d33c-456d-bcca-2bbea50fcead",
                "stock_name":"云南创立投资管理有限公司",
                "stock_type":"法人股东",
                "stock_percent":"",
                "should_capi_items":[

                ],
                "real_capi_items":[

                ]
            }
        ],
        "employees":[
            {
                "seq_no":1,
                "job_title":"监事",
                "name":"闫春光",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":2,
                "job_title":"董事",
                "name":"马军荣",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":3,
                "job_title":"监事",
                "name":"李中照",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":4,
                "job_title":"监事",
                "name":"杨继红",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":5,
                "job_title":"董事长",
                "name":"杨万华",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":6,
                "job_title":"监事",
                "name":"兰丽萍",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":7,
                "job_title":"董事",
                "name":"田恺",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":8,
                "job_title":"董事",
                "name":"和国忠",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":9,
                "job_title":"董事",
                "name":"杨勇",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":10,
                "job_title":"董事",
                "name":"马策",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":11,
                "job_title":"董事",
                "name":"朱英杰",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":12,
                "job_title":"总经理",
                "name":"马策",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":13,
                "job_title":"监事",
                "name":"沈军",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":14,
                "job_title":"董事",
                "name":"李庆华",
                "sex":"",
                "cer_no":""
            },
            {
                "seq_no":15,
                "job_title":"董事",
                "name":"杨先明",
                "sex":"",
                "cer_no":""
            }
        ],
        "branches":[
            {
                "eid":"3ecd5496-4317-49ac-8f7f-47d695010693",
                "name":"云南盐化股份有限公司东川碘盐配送中心"
            },
            {
                "eid":"656cf13a-7cd5-4c88-8605-248cd171aabe",
                "name":"云南盐化股份有限公司乔后盐矿"
            },
            {
                "eid":"c87f0637-59b4-42c8-9e3f-d904f8dab764",
                "name":"云南盐化股份有限公司昆明盐矿"
            },
            {
                "eid":"31997878-4126-40dc-a01b-0030dac29d2e",
                "name":"云南盐化股份有限公司腾冲碘盐配送中心"
            },
            {
                "eid":"b7fc86d3-22ee-46e2-ac41-564b8d311a65",
                "name":"云南盐化股份有限公司洱源碘盐配送中心"
            },
            {
                "eid":"2cf90d8d-42dc-45f5-9076-f728b365e6f4",
                "name":"云南盐化股份有限公司宜良碘盐配送中心"
            },
            {
                "eid":"ae36eb9a-6435-4c3e-b38c-e720db4b2bdc",
                "name":"云南盐化股份有限公司玉溪分公司"
            },
            {
                "eid":"da2bf47a-75f4-40c9-8e65-03520dad658a",
                "name":"云南盐化股份有限公司大理分公司"
            },
            {
                "eid":"0d387033-f69d-4528-a4ee-4ea4b60f485b",
                "name":"云南盐化股份有限公司砚山碘盐配送中心"
            },
            {
                "eid":"2c7be0f1-8432-4b4f-b487-5313b9c1d81d",
                "name":"云南盐化股份有限公司呈贡碘盐配送中心"
            },
            {
                "eid":"e320b5bc-56d5-47db-80c2-50ded0262cfb",
                "name":"云南盐化股份有限公司普洱制盐分公司"
            },
            {
                "eid":"28829837-2e5f-45e5-bda8-1379e35f792c",
                "name":"云南盐化股份有限公司姚安碘盐配送中心"
            },
            {
                "eid":"54f6aefd-51ed-48a7-855d-67d8a18b1382",
                "name":"云南盐化股份有限公司思茅经营部"
            },
            {
                "eid":"915da239-8b97-4075-aa07-25d43d0a7080",
                "name":"云南盐化股份有限公司拓东碘盐配送中心"
            },
            {
                "eid":"5ab433b4-593a-4205-a590-4295d2b48a8a",
                "name":"云南盐化股份有限公司孟连碘盐配送中心"
            },
            {
                "eid":"17eb2025-750f-4d7e-a7b2-251e6a33586a",
                "name":"云南盐化股份有限公司文山分公司"
            },
            {
                "eid":"ff176032-7e92-40d4-a254-57a5d250d32f",
                "name":"云南盐化股份有限公司德宏分公司"
            },
            {
                "eid":"caa4cf53-e568-407a-856f-92eb04b5efa9",
                "name":"云南盐化股份有限公司昭阳区白象碘盐销售部"
            },
            {
                "eid":"03452226-859a-4fcc-8ae6-6552696cd708",
                "name":"云南盐化股份有限公司景东碘盐配送中心"
            },
            {
                "eid":"751a3202-5d51-46de-911e-c311e81ef8c1",
                "name":"云南盐化股份有限公司罗平碘盐配送中心"
            },
            {
                "eid":"2fd7241b-3057-459a-adb9-2854dea7f2de",
                "name":"云南盐化股份有限公司丽江分公司"
            },
            {
                "eid":"257a5036-49a5-4a20-9868-e6b41338221b",
                "name":"云南盐化股份有限公司景谷碘盐配送中心"
            },
            {
                "eid":"a2a2fe2a-59e2-4206-adef-cad52ce77b4b",
                "name":"云南盐化股份有限公司镇雄碘盐配送中心"
            },
            {
                "eid":"90df7592-534f-4819-882d-561292b3f259",
                "name":"云南盐化股份有限公司楚雄分公司"
            },
            {
                "eid":"a0a44d49-159b-46a2-9681-ca6cf76a4373",
                "name":"云南盐化股份有限公司日新碘盐配送中心"
            },
            {
                "eid":"ab490b18-665a-49fc-9534-61e98877f279",
                "name":"云南盐化股份有限公司保山分公司"
            }
        ],
        "address":"云南省昆明市官渡区春城路276号"
    }

    '''
    change_info = u'''
{
    "_id":"5529653186673596081c3470",
    "name":"云南盐化股份有限公司",
    "changerecords":[
        {
            "change_date":"2015年11月30日",
            "change_item":"注册资本(金)变更",
            "seq_no":1,
            "after_content":"27916.4668万人民币",
            "before_content":"18585.1103万人民币"
        },
        {
            "change_date":"2015年11月30日",
            "change_item":"投资人(股权)变更",
            "seq_no":2,
            "after_content":"云南轻纺集团有限公司 出资 8062.1103万人民币;云南有色地质矿业有限公司 出资 715万人民币;云南创立投资管理有限公司 出资 715万人民币;云南省国有资产经营有限责任公司 出资 650万人民币;云南省开发投资有限公司 出资 585万人民币;中国盐业总公司 出资 533万人民币;安宁市工业总公司 出资 325万人民币;社会公众股 出资 7000万人民币;云南省能源投资集团有限公司 出资 9331.3565万人民币;",
            "before_content":"云南轻纺集团有限公司 出资 8062.1103万人民币;云南有色地质矿业有限公司 出资 715万人民币;云南创立投资管理有限公司 出资 715万人民币;云南省国有资产经营有限责任公司 出资 650万人民币;云南省开发投资有限公司 出资 585万人民币;中国盐业总公司 出资 533万人民币;安宁市工业总公司 出资 325万人民币;社会公众股 出资 7000万人民币;"
        },
        {
            "change_date":"2015年11月30日",
            "change_item":"出资比例变更",
            "seq_no":3,
            "after_content":"云南轻纺集团有限公司;云南有色地质矿业有限公司;云南创立投资管理有限公司;云南省国有资产经营有限责任公司;云南省开发投资有限公司;中国盐业总公司;安宁市工业总公司;社会公众股;云南省能源投资集团有限公司;",
            "before_content":"云南轻纺集团有限公司;云南有色地质矿业有限公司;云南创立投资管理有限公司;云南省国有资产经营有限责任公司;云南省开发投资有限公司;中国盐业总公司;安宁市工业总公司;社会公众股;"
        },
        {
            "change_date":"2015年11月30日",
            "change_item":"董事备案",
            "seq_no":4,
            "after_content":"杨勇 马策 田恺 马军荣 杨先明 朱英杰 李庆华 和国忠 杨万华 ",
            "before_content":"黄毓青 吕庆胜 王彤 马策 田恺 李君发 陶其辉 杨勇 陈铁水 "
        },
        {
            "change_date":"2015年11月30日",
            "change_item":"经理备案",
            "seq_no":5,
            "after_content":"马策 ",
            "before_content":"马策 "
        },
        {
            "change_date":"2015年11月30日",
            "change_item":"章程修正案备案",
            "seq_no":6,
            "after_content":"",
            "before_content":"无"
        },
        {
            "change_date":"2015年11月30日",
            "change_item":"监事备案",
            "seq_no":7,
            "after_content":"闫春光 杨继红 兰丽萍 李中照 沈军 ",
            "before_content":"杨金友 杨继红 卢应双 闫春光 兰丽萍 曹立 徐兰 李中照 李杰 "
        },
        {
            "change_date":"2015年11月30日",
            "change_item":"法定代表人变更",
            "seq_no":8,
            "after_content":"杨万华",
            "before_content":"吕庆胜"
        }
    ]
}
    '''
    res = QinxinWeixinEsConvert.convert(basice_info, change_info)
    print json.dumps(res)
